spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      ddl-auto: create-drop # SessionFactory 실행 시 Drop, Create, Alter 실행. 종료 시 Drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true