spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  profiles:
    include: oauth

jwt:
  header: Authorization
  #secret: 추가해야함
  token-validate-in-seconds: 86400