version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql
    ports:
      - 3306:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: Borishop2022!
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ~/Workspaces/mysql/data:/var/lib/mysql # HOST:CONTAINER