drop table if exists product CASCADE;

drop table if exists users CASCADE;

create table product (
   id bigint generated by default as identity,
    name varchar(50) not null,
    detail varchar(255) not null,
    price integer not null,
    sell_status varchar(255),
    stock_number integer not null,
    reg_date timestamp,
    mod_date timestamp,
    primary key (id)
);

create table users (
   id bigint generated by default as identity,
    email varchar(255) not null,
    nickname varchar(255) not null,
    password varchar(255) not null,
    role varchar(255) not null,
    active boolean default true,
    reg_date timestamp,
    mod_date timestamp,
    primary key (id)
);