drop table if exists product CASCADE;

drop table if exists "user" CASCADE;

create table product (
   id bigint generated by default as identity,
    created_at timestamp,
    updated_at timestamp,
    price integer not null,
    product_detail clob not null,
    product_name varchar(50) not null,
    product_sell_status varchar(255),
    stock_number integer not null,
    primary key (id)
);

create table "user" (
   id bigint generated by default as identity,
    created_at timestamp,
    updated_at timestamp,
    active boolean default true,
    email varchar(255) not null,
    nickname varchar(255) not null,
    password varchar(255) not null,
    role varchar(255) not null,
    primary key (id)
);